services:
  postgres:
    image: postgres:16
    container_name: fundavive_db
    restart: always
    environment:
      POSTGRES_USER: fundavive
      POSTGRES_PASSWORD: fundavive123
      POSTGRES_DB: fundavive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fundavive_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://fundavive:fundavive123@postgres:5432/fundavive_db?schema=public"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: fundavive_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
